### ISSUE TITLE
slightly unclear help documentation with included audio in transcode-video.sh

### ISSUE THREAD

**Issue by daDnaK** [donmelton/video-transcoding-scripts#22]
Hi,

looking through the many audio options by now (which are great), it was slightly unclear for me what would happen in the following case (just by the wording of the help):
2 Audio Tracks present, one in German and one in English. Both as AC3 present in the source MKV.

Now the main question for me was, wording wise, whether I'd get 2 audio tracks in the ouptut for the main audio track when supplying the "allow-ac3". As it turned out, it worked great and included the AC3 track as an additional audio track, but the longer I study the documentation, I am more unclear on whether I even needed to supply "--allow-ac3", as this option specifies only "for additional audio tracks". I guess in the main audio track, it's standard behavior that both Stereo Mixdown and AC3 are included? This would make sense then as the --single option would prohibit that.

So my suggestion (in the case that I got it right) is to clarify that the main audio includes the AC3 passthrough as default *unless* --single is specified.
"--allow-ac3" is what good for if I can add audio with the very helpful double option of the --add-audio option? Also the wording of "--allow-ac3" suggests (to me) that it is merely including the AC3 track, and won't include a Stereo version of the track - output would only include the AC3 versions. 

Anyhow, it's a bit unclear to me at the moment. ;-)

**Comment by donmelton** [comment]
Unclear. Got it and I can sympathize. And I'm working on the real problem. I'll explain, but first...

It's true the built-in help doesn't explicitly mention that the main audio track, by default the first track in the input, may be transcoded into two separate tracks, one AAC stereo and one multi-channel surround, in the output. However, the description of the `--single` option, which changes this behavior, strongly implies this. More importantly, this default dual audio track output behavior with the main audio track is covered in great detail within the online README file.

And the built-in help is, I think, very clear that additional audio tracks are added, by default, in AAC stereo. As well as, I think, explaining that using the "double" flag with the `--add-audio` option allows those tracks to be transcoded into two separate tracks, one AAC stereo and one multi-channel surround, just like the main audio track.

Which brings us to the `--allow-ac3` option. Again, I think the built-in help is clear --- this only applies to additional audio tracks. Why? Because AC-3 audio is already allowed by default in the main audio track.

And the `--allow-ac3` option means that the additional audio track, single by default in the output, may be transcoded or passed through as multi-channel AC-3 instead of stereo AAC.

The  `--allow-ac3` option doesn't "double" the additional audio track in the output. That's what the previously described "double" flag is for. In fact, the  `--allow-ac3` is redundant when the "double" flag is used.

Why do both the "double" flag and the `--allow-ac3` option exist? Because other users have explicitly asked for those two different behaviors. Seriously.

Now, could all of this be simpler? Yes. At least, I hope it could. :)

The `transcode-video.sh` API has grown organically over time as I've added features for users. (Most of which I don't use myself.) And I've tried my best to make sure not to break that API during this evolution. That's why it's a bit strange now after three years of development.

What's the solution? Better documentation? That'll help. But what really needs to happen is for me to redesign the tools with a whole new simpler and more flexible API.

And I'm doing that now. :)

But not as the current Bash shell script. The new version will be a Ruby Gem. Not only can I "take a mulligan" on the API that way, but a Ruby Gem will be much easier to install and, more importantly, update. Which has been an even bigger problem for users that my current set of squirrelly options in the API.

I'm closing this now, but feel free to continue commenting.
