### ISSUE TITLE
Linux/Ubuntu problem calcing bitrate in transcode script

### ISSUE THREAD

**Issue by jjaysmith** [donmelton/video-transcoding-scripts#24]
Don, I tweeted with you about this a few weeks ago... sorry for the delay in posting this into GitHub, but my life is a mess at the moment (every day 14 hours, door-to-door, just to do an 8-to-5 job... ugh!).

Anyway, here's the gist of it... transcode script seems works as-is on Ubuntu distributions, EXCEPT

Mar 13:  @donmelton Ubuntu/Mint... stat cmd options differ slightly: have to use `stat -L -c %s "$input"` in place of yours on line 852

Thanks, Don. As I tweeted with you, this script has been an absolute workhorse and solved so many media center issues for me. Now, I spend more time on Plex than I do on cable. :)

**Comment by donmelton** [comment]
Jay,

You're "smithjjay" on Twitter then? My apologies because I lost track of your tweet. Thanks for giving me the March 13 date so I could find it.

No worries about being busy. I have the same problem even being retired. :)

I'm so glad the script is working well for you! Thanks for the feedback. My wife, some neighbors and I were watching my transcoding of "Interstellar (2014)" last night via Plex on a Roku. So I know exactly what you mean. :)

It's funny you opened this issue today since @pefoley2 filed basically the same pull request two days ago: https://github.com/donmelton/video-transcoding-scripts/pull/23

Peter's patch uses the same `stat -L -c %s ` command that you describe. I was unable to make the change yesterday but I should be able to complete it and issue a new release today. I'll leave this issue open until I do.

Thanks again for your help and feedback!

**Comment by donmelton** [comment]
OK, I've updated `transcode-video.sh` to version 5.13 with the fix. Let me know how it's working for you.
