### ISSUE TITLE
make Deinterlacing optional instead of default

### ISSUE THREAD

**Issue by chrisbgp** [donmelton/video-transcoding-scripts#25]
Rather use Decomb. See: https://trac.handbrake.fr/wiki/DeinterlacingGuide#decomb

**Comment by donmelton** [comment]
Chris,

The `deinterlace` filter is not applied by default to all input. It's only applied when the user doesn't specify a frame rate or another filter (e.g. `detelecine` or `decomb`), and when the script detects the input frame rate is exactly `29.97` FPS. That almost never happens for Blu-ray Disc input and only happens about half the time for NTSC (i.e. interlaced, U.S.-style) DVD input. And when the script applies the filter, it also forces the frame rate to `23.976` FPS.

Why is the `deinterlace` filter applied at all if only in those narrow circumstances?

Well, it's not done to remove annoying horizontal line artifacts from interlacing. :) It's done to reduce the frame rate. This makes the transcoding more efficient, meaning (hopefully) higher quality and smaller. It's also done to make the frame rate constant and avoid HandBrake's well-meaning but dangerous variable frame rate mode. Variable frame rates don't interact well with many playback systems and devices.

So, I don't plan to change that behavior. Otherwise many transcoded NTSC DVD inputs just wouldn't look right.

Why don't I use the `decomb` filter instead?

Well, that's not the purpose of the `decomb` filter, despite what HandBrake's documentation says. That documentation is old and unintentionally misleading. For example, the `decomb` filter is noticeably slower than the `deinterlace` filter when applied to real interlaced content. Obviously, you don't want to apply `deinterlace` to non-interlaced content (it _is_ slower in that case), but applying `decomb` all the time, which HandBrake does with many of its presets, is just as stupid.

When should you use the `decomb` filter?

You should apply the `decomb` filter when you see those annoying horizontal line artifacts. And it may actually improve the image. Then again, it may not. You just can't tell ahead of time. Another thing to keep in mind is that combing, i.e. the horizontal line artifacts, can appear in progressive content too. This is an all-too common problem with PAL DVD inputs which were mastered from interlaced sources.

Thanks for the feedback. Keep it coming. :)

**Comment by chrisbgp** [comment]
Thanks for the detailed explaination! I did not know about this as I was only encoding *.MOV from my Iphone and no Blurays etc.

I noticed heavy aliasing when deinterlace was on and that got much better when using decomb instead. It's fine if there is an autodetection, just did not "work" for me ;-)

Thanks for your scripts, they are really helpful.

**Comment by donmelton** [comment]
Glad the scripts are helpful!

You're the third person who's told me they're using them to transcode iPhone output. Thanks for reminding me of that. I'll look into the scenario and see if there's anyway I can detect that kind of input and possibly do something different.
